name: Run Tests

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go 1.23
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.x

      - name: Run Tests
        run: make test
